export enum ComponenteCurricularType {
  EPISTEMOLOGICO = 7,
  FORMATIVO = 9,
  INTERACCION = 10,
  EVALUACION = 11,
  PEDAGOGICO = 8,

  GRADUATE_PROFILE = 23,
  PROGRAM_JUSTIFICATION = 24,
  CURRICULUM = 25,
  RESOURCES = 28,
  PROGRAM_OBJECTIVE = 22,
}
