export enum ProgramModuleTypes {
  SPECIFIC_SUMARY = 76,
  CURRICULAR_COMPONENTS = 77,
  STUDY_PLAN = 78,
  SYLLABUS = 79,
  CURRICULAR_OUTPUT = 80,
  ACADEMIC_CREDITS = 81,
  CORE_AND_SUBCORES = 82,
  PROBLEM_BANK = 98,
  TECHNICAL_TECHNOLOGICAL_PROGRAMS = 99,
  UPDATE_AUTHORIZATIONS = 100,
}

export enum StatusModule {
  IN_UPDATE = 73,
  APPROVED = 74,
  IN_PROJECTION = 75,
  SENT_FOR_REVIEW = 83,
}
