export enum Role {
  DIRECTOR = 1,
  VICERRECTOR = 2,
  ADMINISTRADOR = 3,
  ESTUDIANTE = 4,
  DECANO = 5,
  ASEGURAMIENTO_DE_CALIDAD = 6,
  DOCENTE_COORDINADOR = 7,
  DOCENTE_BASICO = 9,
  ESTUDIANTE_NO_FORMAL = 10,
  ASEGURAMIENTO_DE_CALIDAD_COORDINADOR = 11,
}
